# Generated by Django 5.0.1 on 2024-01-14 05:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_fotografia_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='data',
            field=models.DateTimeField(blank='False', default=datetime.datetime.now),
        ),
    ]
